version: '4.6.0'
services:
  db:
    image: mysql
    container_name: mysql_springboot
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3307:3307"
    volumes:
    - devdojo_data:/var/lib/mysql

volumes:
  devdojo_data: